#!/bin/bash 

clear
echo -e "Clonando dotfiles..."
sleep 1
rm -rf ~/.zshrc
rm -rf ~/.p10k.zsh
mkdir ~/.local/bin
git clone https://github.com/mxhectorvega/dotfilesarchlinux /tmp/dots
cp -R /tmp/dots/.config/* ~/.config
cp /tmp/dots/.zshrc ~/.zshrc
cp /tmp/dots/.p10k.zsh ~/.p10k.zsh
git clone https://github.com/ekistece/GetExtensions.git
clear
echo -e "Ahora escribe contraseña root para cambiar de Shell a ZSH"
sudo pacman -S python-pip --noconfirm --needed
pip install ./GetExtensions --user
rm -rf ~/GetExtensions
chsh -s /bin/zsh
clear
echo -e "Configs ZSH, Ranger, Kitty y Neovim cargadas!"
sleep 1
echo ""
echo -e "Contribuye en paypal.me/hivz"
sleep 3
pkill -9 kitty
